config/routes.rb
Rails.application.routes.draw do

  resources :chat_messages
  resources :guest_session_associations
  resources :jam_sessions
  resources :users

  get 'sessions/new'

  get 'users/new'
  resources :users
  root 'creatives#index'
  get 'loginpage', to: 'static_pages#loginpage' # OLD
  get 'display_map', to: 'application#display_map'  # OLD
  get  '/choosetype',    to: 'static_pages#choosetype'
  get  '/signup',  to: 'users#new'
  get   '/login',   to: 'sessions#new'
  get '/new_event', to: 'jam_sessions#new'
  get '/jam_session', to: 'jam_sessions#show'
  get 'profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit'
  get '/profile/edit', to: 'users#edit'
post   '/login',   to: 'sessions#create'
get 'creatives/index'
get '/logout',  to: 'sessions#destroy'
post '/signup',  to: 'users#create'
get 'tab_show', to: 'jam_sessions#tab_show'
get 'tabs_index', to: 'jam_sessions#tabs_index'
get '/tab_show_chords', to: 'jam_sessions#tab_show_chords'
delete '/guest_session_association', to: 'guest_session_associations#destroy'
end

app/models/jam_session.rb
class JamSession < ApplicationRecord
  has_many :chat_messages
  has_many :guest_session_associations
  geocoded_by :address
  after_validation :geocode
  def host_name(host_id)
    @name= User.where(id:host_id).pluck(:name)
  end

  def self.old
    if (self.end_time>=DateTime.now.change(offset: "-3000")-30.minutes)
      return false
    else
      return true
  end
  end

  def self.search(search_host, search_name, search_genre, search_time)

    @jam_sessions=JamSession.where('end_time >= ?',DateTime.now.change(offset: "-3000")-30.minutes)
    if (!search_host.blank?)
      user_id=User.where("name LIKE ?", "%#{search_host}%").pluck(:id)
      @jam_sessions= @jam_sessions.where(host_id:user_id)
    end
    if (!search_name.blank?)
      @jam_sessions= @jam_sessions.where("name LIKE ?", "%#{search_name}%").or(@jam_sessions.where("description LIKE ?", "%#{search_name}%"))
    end
    if (!search_genre.blank?)
      @jam_sessions= @jam_sessions.where(genre:search_genre)
    end
    if (!search_time.blank?)
      if search_time=='1'
        # now
        # starting within 30 minutes and ending after current time
        upper_bound=DateTime.now+ 30.minutes
      elsif search_time =='2'
        #3 hours
        # starting within the next 3 hours and ending after current time
        upper_bound =DateTime.now + 3.hours
      elsif search_time == '3'
        #12 hours
        #starting within the next 12 hours and ending after current time_search
        upper_bound =DateTime.now + 12.hours
      elsif search_time =='4'
        #24 hours
        #starting within the next 24 hours and ending after current time
        upper_bound =DateTime.now + 24.hours
      end
      @jam_sessions= @jam_sessions.where('start_time >= ? AND start_time <= ? AND end_time  > ? OR (end_time < ? AND end_time > ?)', DateTime.now.change(offset: "-3000"), upper_bound.change(offset: "-3000"), DateTime.now.change(offset: "-3000"), upper_bound.change(offset: "-3000"), DateTime.now.change(offset: "-3000") )
    end
    @jam_sessions
  end


  def self.host_search(search)
    return nil if search.blank?
    user_id=User.where("name LIKE ?", "%#{search}%").pluck(:id)
    JamSession.where(host_id:user_id)
  end
  def self.name_search(search)
    return nil if search.blank?
    JamSession.where("name LIKE ?", "%#{search_query}%").or(JamSession.where("description LIKE ?", "%#{search_query}%"))
  end
  def self.count_p
    GuestSessionAssociation.where(jam_session_id:self.id, player:TRUE).count
  end
  def self.count_l
    GuestSessionAssociation.where(jam_session_id:self.id, player:FALSE).count
  end
  scope :search_query_jam_name, lambda { |search_query_jam_name|
    return nil if search_query.blank?
    JamSession.where("name LIKE ?", "%#{search_query}%").or(JamSession.where("description LIKE ?", "%#{search_query}%")).or(JamSession.where("address LIKE ?", "%#{search_query}%"))
  }
  scope :search_query_host_name, lambda { |search_query_host_name|
    return nil if search_query.blank?
    user_id=User.where("name LIKE ?", "%#{search_query_host_name}%").pluck(:id)
    JamSession.where("host_id LIKE ?", "%#{user_id}%")
  }
  scope :select_genre, lambda { |select_genre|
    JamSession.where(genre: [select_genre])
  }
  def self.options_for_select
    ["pop","rock","jazz","soul","metal","house"]
  end
  def search_near
    @userLocation = request.location #gets the ip of the user
  end

  has_attached_file :audio_file
  validates_attachment :audio_file, :content_type => {:content_type => ['audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio']},
   :file_name => { :matches => [ /mp3\Z/]}


end

app/controllers/jam_sessions_controller.rb
require 'nokogiri'
require 'open-uri'
require 'json'
class JamSessionsController < ApplicationController
  before_action :set_jam_session, only: [:show, :edit, :update, :destroy]

  # GET /jam_sessions
  # GET /jam_sessions.json
  def index
     @your_sessions= JamSession.where(id: GuestSessionAssociation.where(user_id: current_user.id).pluck(:jam_session_id)).order(:name).paginate(page: params[:your_sessions_page])
     if params[:location].present?
       @jam_sessions= JamSession.near(params[:location], params[:distance] || 10).search(params[:host_search],params[:name_search], params[:genre_search], params[:time_search]).order(:name).paginate(:page => params[:jam_sessions_page])
     else
         @jam_sessions = JamSession.search(params[:host_search],params[:name_search], params[:genre_search], params[:time_search]).order(:name).paginate(:page => params[:jam_sessions_page])
     end
  end

  def tabs_index
    client = Geetar::Client.new
    if params[:tab]!=nil
        @search = Geetar::Search.new(client, params[:tab])
    end
    @chords=params[:chords]
  end

  def set_audio
    @sound = jam_session_params[:audio]
  end

  def tab_show
    #code to use the Songsterr API. The API did not meet our needs so we decided not to use it.
    #Instead we used the UltimateGuitar API.
    # @url=params[:url]
    # require 'net/http'
    # require 'json'
    # @result = Net::HTTP.get(URI.parse('https://www.songsterr.com/a/ra/songs/byartists.xml?artists=Metallica,"Led%20Zeppelin"'))
    # @result2 = Net::HTTP.get(URI.parse('https://www.songsterr.com/a/wa/bestMatchForQueryString?s={all i want}&a={kodaline}'))
    # # @result=JSON.parse(@result.replace(/&quot;g,'"'))
    # # @artists=JSON.parse(@result)
    #
    # # # result = Net::HTTP.get(URI.parse('http://www.example.com'), '/about.html')
    # # render :xml => @result
    # xml =  Nokogiri::XML.parse(@result)
    # # @artists = xml.xpath("//artist//name")
    # @songs=xml.xpath("//title")
    # @song_ids=xml.xpath("//@id")
    # @song_id_array=Array.new
    # @song_ids.each do |id|
    #   @song_id_array.push(id)
    # end
    # @artists_list=Array.new
    # @artists = xml.xpath("//artist//name")
    # @artists.each do |artist|
    #     @artists_list.push(artist.text)
    # end
  end
  def tab_show_chords
      @chords=params[:chords]
      @tab_name=params[:tab_name]

  end
  def all_sessions_json
   render :text=>(@sessions).to_json
  end

  # GET /jam_sessions/1
  # GET /jam_sessions/1.json
  def show
    @name = User.where(id:@jam_session.host_id).pluck(:name)
    @users= User.where(id: GuestSessionAssociation.where(jam_session_id: @jam_session.id).distinct.pluck(:user_id))
    @jam_players_count= GuestSessionAssociation.where(jam_session_id: @jam_session.id,player:true).distinct.count
    @jam_listeners_count= GuestSessionAssociation.where(jam_session_id: @jam_session.id,player:false).distinct.count
    @chat_messages = ChatMessage.where(jam_session_id: @jam_session.id).sort_by { |message| message.created_at}
  end


  # GET /jam_sessions/new
  def new
    @jam_session = JamSession.new()
  end

  # GET /jam_sessions/1/edit
  def edit
  end

  # POST /jam_sessions
  # POST /jam_sessions.json
  def create
    @jam_session = JamSession.new(jam_session_params)
    @jam_session.host_id=session[:user_id]
    # @jam_session.audio_file=@sound
    # @jam_session.name=@sound
    respond_to do |format|
      if @jam_session.save

        format.html { redirect_to jam_sessions_path, notice: 'Jam session was successfully created.' }
        format.json { render :show, status: :created, location: @jam_session }

      else
        format.html { render :new }

        format.json { render json: @jam_session.errors, status: :unprocessable_entity }
      end
    end
    @association=GuestSessionAssociation.new(user_id:@jam_session.host_id, jam_session_id: @jam_session.id, player:true)
    @association.save

  end

  # PATCH/PUT /jam_sessions/1
  # PATCH/PUT /jam_sessions/1.json
  def update
    respond_to do |format|
      if @jam_session.update(jam_session_params)
        format.html { redirect_to @jam_session, notice: 'Jam session was successfully updated.' }
        format.json { render :show, status: :ok, location: @jam_session }
      else
        format.html { render :edit }
        format.json { render json: @jam_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jam_sessions/1
  # DELETE /jam_sessions/1.json
  def destroy
    @jam_session.destroy
    @guests= GuestSessionAssociation.where(jam_session_id: @jam_session.id)
    @guests.destroy_all
    respond_to do |format|
      format.html { redirect_to jam_sessions_path }
      format.json { head :no_content }
    end
  end

  def host_name(host_id)
    JamSession.host_name(host_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jam_session
      @jam_session = JamSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jam_session_params
      params.require(:jam_session).permit(:longitude, :latitude, :host_id, :max_players, :max_listeners, :name, :description, :address, :tab,:url, :audio, :audio_file,:sound, :genre, :host_search, :name_search, :your_sessions_page, :jam_sessions_page, :reset,:chords,:tab_name, :genre_search, :start_time, :end_time, :time_search)
    end
end

app/helpers/jam_sessions_helper.rb
module JamSessionsHelper
end

app/views/jam_sessions/_bg_primary.html.erb
<header>
<section class="bg-primary" id="jam-sessions">
  <body>
    <div class="py-5"></div>
    <div class="py-5">
      <div class="container">
          <div class="col-md-3"  style="padding-right:30px">
              <div class="row">
                <div class="center jumbotron" style="color:black">
                  <div class="card">
                    <div class="card-body"
                      <h4>Filter your search!</h4>
                    <%= form_tag(jam_sessions_path, :method => "get", id: "jam-search") do %>
                      <%= text_field_tag :host_search, params[:host_search], :id=>"host", placeholder: "Search Host" %>
                      <%= text_field_tag :name_search, params[:name_search],:id=>"name-search", placeholder: "Search Name, Description" %>

                      <%= select_tag(:genre_search, options_for_select([['Pop', 'pop'], ['Rock', 'rock'],["Jazz","jazz"],["Soul","soul"],["Metal","metal"],["House","house"],["Classical","classical"]]),:include_blank=>true, id:"genre") %>
                      <%= select_tag(:time_search, options_for_select([['Now', 1], ['Next 3 Hours', 2],["Next 12 Hours",3],["Next 24 Hours ",4]]),:include_blank=>true, id:"time") %>

                      <%=button_tag "Reset Filters", :type => 'button', :onclick=>"ClearFields();", class:'btn btn-primary btn-xl page-scroll'%>
                      <%= submit_tag "Search", :name => nil,class:'btn btn-primary btn-xl page-scroll' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <script>
            function ClearFields() {
                 document.getElementById("host").value = "";
                 document.getElementById("name").value = "";
                 document.getElementById("genre").value = "";
                 document.getElementById("time").value = "";
            }
            </script>
          <div class="row">

              <div class="center jumbotron" style="color:black">
              <div class="card">
              <div class="card-body"style='height: 340px;'>
                <h4>Your Sessions</h4>
                <p class=" p-y-1">    <%= render(
                      partial: 'jam_sessions/yoursessions',
                      locals: { jam_sessions: @jam_sessions }
                    )%></p>
              </div>
              </div>
              <br><br>
              <br><br>

              <div class="row">
              <%= link_to 'Find Chords', "#modal-for-tab-index", "data-toggle" => "modal", class: 'btn btn-primary btn-xl page-scroll' %>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-3">
              <div class="row">
              <div class="center jumbotron" style="color:black">
              <div class="card">
              <div class="card-body"style='height: 650px;'>
                <h4>Jam Sessions</h4>
                <p class=" p-y-1" style="float:left">  <%= render(
                  partial: 'jam_sessions/list',
                  locals: { jam_sessions: @jam_sessions }
                ) %></p>
              </div>
              </div>
              <br>
              <br>
              <br>
              <div class="row"><%= link_to "Schedule A Session", "#modal-to-create-jam_session", "data-toggle" => "modal", class: 'btn btn-primary btn-xl page-scroll'%></div>
              </div>

          </div>
          </div>

                <div class="col-md-6" style="color:black">
                <div id="map" style='width: 100%; height: 800px; min-height: xxx; overflow: hidden; float: right; padding-right: 0px; margin: 0px'></div></div>
          </div>

      </div>
    </div>
    <div class="py-5"></div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script type="text/javascript">

    var locations = [];
    var links = [];
    <% @jam_sessions.each do |location| %>
      var place = [<%= location.latitude %>, <%= location.longitude %>, "<%= location.name %>" ];
      locations.push(place);
      var link_id =  <%= location.id %>
      links.push(link_id);
    <% end %>
    var sliderA = new Slider("#ex16a", { min: 0, max: 10, value: 0, focus: true });
    var sliderB = new Slider("#ex16b", { min: 0, max: 10, value: [0, 10], focus: true });
      function initMap(){
          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 13,
            center: new google.maps.LatLng(42.37, -71.2),
            mapTypeId: google.maps.MapTypeId.ROADMAP
          });

          //var infowindow = new google.maps.InfoWindow();

          var marker, i;

          for (i = 0; i < locations.length; i++) {
            marker = new google.maps.Marker({
              position: new google.maps.LatLng(locations[i][0], locations[i][1]),
              map: map,
              name: locations[i][2]
           });
           attachInfowindow(marker);
}

         function attachInfowindow(marker) {
          var infowindow = new google.maps.InfoWindow({
            content: marker.name + ': <%= j link_to "Session Info", "#modal-for-jam_session\\:1", "data-toggle" => "modal" %>'
          });

          marker.addListener('click', function() {
            infowindow.open(marker.get('map'), marker);
          });
        }



      }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_E9YsDaw5Jfj1HC4WKNjepV_maFzCVAQ&callback=initMap"
    type="text/javascript"></script>
  </body>

</section>
</header>
<%= render 'jam_sessions/tabs_index_modal'%>
<%@jam_sessions.each do |jam_session|%>
<%= render 'jam_sessions/jam_modal', jam_session: jam_session %>
<% end %>

<%= render 'jam_sessions/create_jam_modal' %>

<%= render 'jam_sessions/tabs_index_modal'%>

<%= render 'users/edit_modal' %>

app/views/jam_sessions/_form.html.erb
<%= form_with(model: jam_session, local: true) do |form| %>
  <% if jam_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jam_session.errors.count, "error") %> prohibited this jam_session from being saved:</h2>

      <ul>
      <% jam_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :jam_session_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :max_players %>
    <%= form.number_field :max_players, id: :jam_session_max_players %>
  </div>

  <div class="field">
    <%= form.label :max_listeners %>
    <%= form.number_field :max_listeners, id: :jam_session_max_listeners %>
  </div>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :jam_session_description %>
  </div>
  	</head>
  	<body>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jam_sessions/_hearts.html.erb
<button class="close" id="hearts-for-jam_session-<%=jam_session.id%>">
	<span class="small text-danger">
		<% if Heart.find_by(user_id: current_user.id, jam_session_id: jam_session.id) %>
			<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
		<% else %>
			<span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
		<% end %>


		<%= Heart.where(jam_session_id: jam_session.id).count %>
	</span>
</button>

app/views/jam_sessions/_jam_modal.html.erb
<% id = "modal-for-jam_session:#{jam_session.id}" %>

<div class="modal fade" id='<%= id %>', title="Jam Session">
	<div class="modal-dialog" role="document">
		<div class="modal-content">

			<div class="modal-header">
				<div>
					<h4>
						<%= render 'hearts', jam_session: jam_session %>
						<small>
							<span class="glyphicon glyphicon-music" aria-hidden="true"></span>
							Jam Session
						</small>
					</h4>
				</div>

				<script>
					$($('#hearts-for-jam_session-<%=jam_session.id%>').click(function() {
						<% Heart.toggle current_user, jam_session %>
						$('#hearts-for-jam_session-<%=jam_session.id%>').replaceWith("<%= j render 'hearts', jam_session: jam_session %>");
					}));
				</script>

				<h3>
					<%= jam_session.name %>
				</h3>
				<div class="text-center">
					<% host = User.find(jam_session.host_id) %>
					<span class="small">
						<%= image_tag host.avatar.url(:thumb), class: "img-circle", style: "width: 16px; height: 16px;" %>
					</span>
					Hosted by
					  <%= render 'users/user_profile_modal', user: host %>
					<% if host.id == current_user.id %>
					<%= link_to 'Me', "#modal-for-user-#{current_user.id}", "data-dismiss" => "modal",  "data-toggle" => "modal"%>
					<% else %>
					<%= link_to host.name, "#modal-for-user-#{host.id}", "data-dismiss" => "modal", "data-toggle" => "modal" %>
					<% end %>
					<br>
					<%=jam_session.genre%> <span class="glyphicon glyphicon-music" aria-hidden="true"></span>

				</div>
				<br>


				<div class="row text-center">
					<div class="col-sm-6">
						<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
						<e>
							<%=jam_session.address%>

							</address>
						</e>
					</div>

					<div class="col-sm-6">
						<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
						<e>
							<%start_t=jam_session.start_time%>
							<%end_t=jam_session.end_time%>
							<%if (!start_t.blank?)%>
								<%=start_t.strftime("%I:%M %p")%> -
							<%end%>
							<%if (!end_t.blank?)%>
								<%=end_t.strftime("%I:%M %p")%>
							<%end%>

						</e>
					</div>
				</div>
			</div>

			<div class="modal-body">

				<div class="row text-center">
					<% if jam_session.max_players.to_i != 0 %>
						<div class="col-sm-6">
							<span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>
							Players:
							<%= GuestSessionAssociation.where(jam_session_id: jam_session.id, player: true).distinct.count-1 %>
							/
							<%= jam_session.max_players %>
						</div>
					<% end %>

					<% if jam_session.max_listeners.to_i != 0 %>
						<div class="col-sm-6">
							<span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>
							Listeners:
							<%= GuestSessionAssociation.where(jam_session_id: jam_session.id, player: false).distinct.count %>
							/
							<%= jam_session.max_listeners %>
						</div>
					<% end %>
				</div>

				<div class="row text-center">
					<% if jam_session.max_players.to_i != 0 %>
						<div class="col-sm-6">
							<% percent_players = 100 * (GuestSessionAssociation.where(jam_session_id: jam_session.id, player: true).distinct.count.to_i-1) / jam_session.max_players.to_i %>

							<div class="progress">
	  						<div class="progress-bar progress-bar-warning progress-bar-striped" role="progressbar"
								style='width: <%= percent_players %>%'>
	  						</div>
							</div>
						</div>
					<% else %>
						<% percent_players = 100 %>
					<% end %>

					<% if jam_session.max_listeners.to_i != 0 %>
						<div class="col-sm-6">
							<% percent_listeners = 100 * GuestSessionAssociation.where(jam_session_id: jam_session.id, player: false).distinct.count.to_i / jam_session.max_listeners.to_i %>

							<div class="progress">
	  						<div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar"
								style='width: <%= percent_listeners %>%'>
	  						</div>
							</div>
						</div>
					<% else %>
						<% percent_listeners = 100 %>
					<% end %>
				</div>

				<%if (jam_session.audio_file_file_name != nil) %>
				<audio controls>
			 	<source src="<%= jam_session.audio_file %>" type="audio/mp3">
				</audio>
				<%end%>

				<br>
				<em>
					<%= jam_session.description %>
				</em>
				<br>

				</address>
			</div>

			<div class="modal-footer">

				<% if jam_session.host_id == current_user.id %>
					<%= link_to "Cancel Jam Session", jam_session, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to cancel this jam session?' } %>
				<% elsif guest_session_association = GuestSessionAssociation.find_by(user_id: current_user.id, jam_session_id: jam_session.id) %>
					<%= link_to "Leave Jam Session", guest_session_association, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to leave this jam session?' } %>
				<% else %>
					<% if percent_players < 100 && jam_session.max_players.to_i != 0 %>
						<%= link_to "Attend as Player", guest_session_association_path(id: jam_session.id, player: TRUE), class: 'btn btn-warning' %>
					<% end %>
					<% if percent_listeners < 100 && jam_session.max_listeners.to_i != 0 %>
						<%= link_to "Attend as Listener", guest_session_association_path(id: jam_session.id, player: FALSE), class: 'btn btn-info' %>
					<% end %>
				<% end %>

				<%= link_to "#modal-for-chat_message\\:#{jam_session.id}", class: "btn", "data-toggle" => "modal" do %>
    			<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
				<% end %>

			</div>

		</div>
	</div>
</div>
<%= render 'users/user_profile_modal', user: current_user %>
<%= render 'chat_messages/chat_modal', jam_session: jam_session %>

app/views/jam_sessions/_tabs_index_modal.html.erb
<% id = "modal-for-tab-index" %>

<div class="modal fade" id='<%= id %>', title="Tab Index">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
        <h1>Chords and Tabs</h1>
        <br><br>
      </div>
      <div class="modal-body">
        <div  align="center">
        <%= form_tag(tabs_index_path, method: :get) do %>
          <%= text_field_tag :tab, params[:tab],placeholder: 'Search chords and tabs' %>
          <%= submit_tag 'Search',name: nil, class: 'btn btn-primary btn-xl page-scroll'%>
					<!-- link_to "Search", "#modal-for-tab-list","data-toggle" => "modal",class: 'btn btn-primary btn-m page-scroll', style:'width:50%; height:100%'  -->
					<!-- render 'jam_sessions/tab_show_modal', tab: params[:tab]  -->

        <% end %>
        </div>
        <br><br>

      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>

app/views/jam_sessions/index.html.erb
<%= render 'navbar' %>
<%= render 'display_page' %>

app/views/jam_sessions/index.js.erb
 $("#jam_sessions").html("<%= escape_javascript(render(partial: 'jam_sessions/list', locals: { jam_sessions: @jam_sessions })) %>");

$('#post').click(function() { });
$("#one").html("<%= j (render 'jam_sessions/list') %>");
$("#two").html("<%= j (render 'jam_sessions/yoursessions') %>");

app/views/jam_sessions/tabs_index.html.erb
<%= render 'navbar' %>

<h2 style="text-align:center;">Chords and Tabs</h2>
  <table align="center",style="text-align:center;">
    <%if (@search != nil && @search.results!=nil)%>
      <th>Title</th>
      <th>Artist</th>
      <th>Tab Type</th>
      <%@search.results.each do |result|%>
      <tr>
        <td><%=link_to result.title, tab_show_chords_path(chords: result.content.html_safe, tab_name:result.title)%></td>
        <td><%=result.artist%>  </td>
        <td><%=result.tab_type%> </td>
      </tr>
      <%end%>
    <%end%>
  </table>