config/routes.rb
Rails.application.routes.draw do

  resources :chat_messages
  resources :guest_session_associations
  resources :jam_sessions
  resources :users

  get 'sessions/new'

  get 'users/new'
  resources :users
  root 'creatives#index'
  get 'loginpage', to: 'static_pages#loginpage' # OLD
  get 'display_map', to: 'application#display_map'  # OLD
  get  '/choosetype',    to: 'static_pages#choosetype'
  get  '/signup',  to: 'users#new'
  get   '/login',   to: 'sessions#new'
  get '/new_event', to: 'jam_sessions#new'
  get '/jam_session', to: 'jam_sessions#show'
  get 'profile', to: 'users#show'
  get '/profile/edit', to: 'users#edit'
  get '/profile/edit', to: 'users#edit'
post   '/login',   to: 'sessions#create'
get 'creatives/index'
get '/logout',  to: 'sessions#destroy'
post '/signup',  to: 'users#create'
get 'tab_show', to: 'jam_sessions#tab_show'
get 'tabs_index', to: 'jam_sessions#tabs_index'
get '/tab_show_chords', to: 'jam_sessions#tab_show_chords'
delete '/guest_session_association', to: 'guest_session_associations#destroy'
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Come find some great friends and music!</h2>
                <hr class="light">
                <p class="text-faded">Our mission is to spread the joy of music by allowing our users to find spontaneous jam sessions around them! Schedule a jam session now or choose to attend.
                </p>
                    <% if logged_in? %>
                <%= link_to 'Get Started!', jam_sessions_path, "data-toggle" => "modal", class: "btn btn-default btn-xl" %>

                            <% else %>
  <%= link_to 'Get Started!', "#signup-modal", "data-toggle" => "modal", class: "btn btn-default btn-xl" %>

                            <% end %>
            </div>
        </div>
    </div>
</section>
<%= render 'sessions/login_modal' %>
<%= render 'users/signup_modal' %>
<%= render 'users/edit_modal' %>

app/views/creatives/_header.html.erb
<header>
  <section id="page-top">
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Follow The Music</h1>

            <hr>
            <p>  <a class= "page-scroll" href="#about"  style="color:white;" >A place for spontaneous jam sessions, concerts, and new friends!</a>
            </p>
            <% if logged_in? %>
            <%= link_to 'Schedule or Find A Jam Session', jam_sessions_path, "data-toggle" => "modal", class: "btn btn-primary btn-xl page-scroll" %>

                    <% else %>
                    <%= link_to 'Schedule or Find A Jam Session', "#signup-modal", "data-toggle" => "modal", class: "btn btn-primary btn-xl page-scroll" %>

                    <% end %>
                  <br>
                  <br>
        </div>
    </div>
  </section>
</header>
<%= render 'users/edit_modal' %>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a class="navbar-brand page-scroll" href="#page-top"> <span><%= image_tag("icon.png", size: "30x30", :alt => "Lizzie") %></span>  Follow The Music</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

            <!-- HOME -->

            <li>
                <a class="page-scroll" href="#about"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> About</a>
            </li>
            <% if logged_in? %>

              <!-- JAM SESSIONS -->
              <li class="nav-item">
                <%= link_to '<span class="glyphicon glyphicon-music" aria-hidden="true"></span>
                Jam Sessions'.html_safe, jam_sessions_path %>
              </li>

              <li class="nav-item">
                <%= link_to '<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              '.html_safe + current_user.name, "#modal-for-user-#{current_user.id}", "data-toggle" => "modal" %>

              </li>

              <li class="nav-item">
                <%= link_to '<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                Log Out'.html_safe, logout_path, method: :get, data: { confirm: 'Are you sure you wish to log out?' } %>
              </li>

              <!-- USER (DROPDOWN) -->

            <% else %>

              <!-- SIGN UP -->
              <li class="nav-item">
                <%= link_to '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Sign Up'.html_safe, "#signup-modal", :class => "btn", "data-toggle" => "modal" %>
              </li>

              <!-- LOG IN -->
              <li class="nav-item">
                <%= link_to '<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                Log In'.html_safe, "#login-modal", :class => "btn", "data-toggle" => "modal" %>
              </li>

            <% end %>

          </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<%= render 'sessions/login_modal' %>
<%= render 'users/signup_modal' %>
<% if logged_in? %>
  <%= render 'users/user_profile_modal', user: current_user %>
<% end %>

app/views/creatives/_services.html.erb
<style>
.img-circular{
 width: 150px;
 height: 150px;
 background-size: cover;
 display: block;
 border-radius: 100px;
 -webkit-border-radius: 100px;
 margin: auto;
 -moz-border-radius: 100px;

}
</style>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Our Team</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag("lizzie.jpg", :alt => "Lizzie", :class=> "img-circular") %>
                    <h3>Lizzie Koshelev</h3>
                    <p class="text-muted">A senior at Brandeis University with a great passion for coding and music!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                      <%= image_tag("deniz.jpg", :alt => "Lizzie", :class=> "img-circular") %>
                    <h3>Deniz Amado</h3>
                    <p class="text-muted"> A senior at Brandeis University that loves singing and coding!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                  <%= image_tag("abhishek.jpg", :alt => "Lizzie", :class=> "img-circular") %>
                    <h3>Abhishek Kulkarni</h3>
                    <p class="text-muted">  A senior at Brandeis University that codes</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag("devi.jpg", :alt => "Lizzie",:class=> "img-circular") %>
                    <h3>Devi Acharya</h3>
                    <p class="text-muted">  She codes and  musics too</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/creatives/index.html.erb
<%= render 'creatives/navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'services' %>

<% if get_failed_attempt == 'login' %>
	<script>
		$($('#login-modal').modal("show"))
	</script>
<% elsif get_failed_attempt == 'signup' %>
	<script>
		$($('#signup-modal').modal("show"))
	</script>
<% end %>